dist: trusty
sudo: required
group: deprecated-2017Q4

stages:
  - api
  - client
  - mobile
  - test
  - test1
  - deploy

jobs:
  include:
    - stage: client
      script: echo $TRAVIS_PULL_REQUEST_BRANCH
    - script: echo ./test 1 # uses the default stage name "test"
    - script: echo ./test 2
    - stage: deploy
      script: echo ./deploy mobile
    - script: echo ./deploy api 
    - stage: test
      script: echo test3
    - stage: test1
      script: echo different test1
    - stage: deploy
      script: echo $TRAVIS_BRANCH
      script: if [[ ${TRAVIS_BRANCH} != "master" ]]; then travis_terminate 0; fi
    - stage: mobile
      script: echo mobile step
    - stage: api
      script: echo api step
